const SET_CURRENT_ANSWER = 'SET_CURRENT_ANSWER';
const SET_CURRENT_QUESTION = 'SET_CURRENT_QUESTION';
const SET_ERROR = 'SET_ERROR';
const SET_SHOW_RESULTS = 'SET_SHOW_RESULTS';
const SET_ANSWERS = 'SET_ANSWERS';
const RESET_QUIZ = 'RESET_QUIZ';